require("theszar.options")
require("theszar.keymaps")
require("theszar.autocmd")

require("theszar.packer")
require("theszar.plugins.lsp")
require("theszar.plugins.cmp")
require("theszar.plugins.colortheme")
require("theszar.plugins.lualine")
require("theszar.plugins.treesitter")
require("theszar.plugins.telescope")
require("theszar.plugins.toggleterm")
require("theszar.plugins.nvim-tree")
require("theszar.plugins.comment")
require("theszar.plugins.autopairs")
require("theszar.plugins.project")
